services:
  audio-scalogram-api:
    image: ${AUDIO_SCALOGRAM_IMAGE:-ghcr.io/mario42004/d-ml-audio-scalogram-api:latest}
    container_name: audio-scalogram-api
    ports:
      - "8001:8001"
    environment:
      APP_ENV: production
      APP_PORT: 8001
    restart: unless-stopped
